/**
 * This class is generated by jOOQ
 */
package server.jooq.tables;

import server.jooq.Debtmanager;
import server.jooq.Keys;
import server.jooq.tables.records.BankTransfersRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankTransfers extends org.jooq.impl.TableImpl<BankTransfersRecord> {

	private static final long serialVersionUID = -1637106329;

	/**
	 * The reference instance of <code>debtmanager.bank_transfers</code>
	 */
	public static final BankTransfers BANK_TRANSFERS = new BankTransfers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<BankTransfersRecord> getRecordType() {
		return BankTransfersRecord.class;
	}

	/**
	 * The column <code>debtmanager.bank_transfers.id</code>.
	 */
	public final org.jooq.TableField<BankTransfersRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>debtmanager.bank_transfers.budget_id</code>.
	 */
	public final org.jooq.TableField<BankTransfersRecord, java.lang.Integer> BUDGET_ID = createField("budget_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>debtmanager.bank_transfers.who</code>.
	 */
	public final org.jooq.TableField<BankTransfersRecord, java.lang.Integer> WHO = createField("who", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>debtmanager.bank_transfers.whom</code>.
	 */
	public final org.jooq.TableField<BankTransfersRecord, java.lang.Integer> WHOM = createField("whom", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>debtmanager.bank_transfers.amount</code>.
	 */
	public final org.jooq.TableField<BankTransfersRecord, java.math.BigDecimal> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2).nullable(false), this, "");

	/**
	 * The column <code>debtmanager.bank_transfers.paid</code>.
	 */
	public final org.jooq.TableField<BankTransfersRecord, java.lang.Boolean> PAID = createField("paid", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * Create a <code>debtmanager.bank_transfers</code> table reference
	 */
	public BankTransfers() {
		this("bank_transfers", null);
	}

	/**
	 * Create an aliased <code>debtmanager.bank_transfers</code> table reference
	 */
	public BankTransfers(java.lang.String alias) {
		this(alias, BankTransfers.BANK_TRANSFERS);
	}

	private BankTransfers(java.lang.String alias, org.jooq.Table<BankTransfersRecord> aliased) {
		this(alias, aliased, null);
	}

	private BankTransfers(java.lang.String alias, org.jooq.Table<BankTransfersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Debtmanager.DEBTMANAGER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<BankTransfersRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_BANK_TRANSFERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<BankTransfersRecord> getPrimaryKey() {
		return Keys.BANK_TRANSFERS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<BankTransfersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<BankTransfersRecord>>asList(Keys.BANK_TRANSFERS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<BankTransfersRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<BankTransfersRecord, ?>>asList(Keys.BANK_TRANSFERS__BANK_TRANSFERS_BUDGET_ID_FKEY, Keys.BANK_TRANSFERS__BANK_TRANSFERS_WHO_FKEY, Keys.BANK_TRANSFERS__BANK_TRANSFERS_WHOM_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfers as(java.lang.String alias) {
		return new BankTransfers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public BankTransfers rename(java.lang.String name) {
		return new BankTransfers(name, null);
	}
}
