/**
 * This class is generated by jOOQ
 */
package server.jooq.tables;

import server.jooq.Debtmanager;
import server.jooq.Keys;
import server.jooq.tables.records.BudgetsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Budgets extends org.jooq.impl.TableImpl<BudgetsRecord> {

	private static final long serialVersionUID = 1770768548;

	/**
	 * The reference instance of <code>debtmanager.budgets</code>
	 */
	public static final Budgets BUDGETS = new Budgets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<BudgetsRecord> getRecordType() {
		return BudgetsRecord.class;
	}

	/**
	 * The column <code>debtmanager.budgets.id</code>.
	 */
	public final org.jooq.TableField<BudgetsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>debtmanager.budgets.name</code>.
	 */
	public final org.jooq.TableField<BudgetsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>debtmanager.budgets.description</code>.
	 */
	public final org.jooq.TableField<BudgetsRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>debtmanager.budgets.owner_id</code>.
	 */
	public final org.jooq.TableField<BudgetsRecord, java.lang.Integer> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>debtmanager.budgets</code> table reference
	 */
	public Budgets() {
		this("budgets", null);
	}

	/**
	 * Create an aliased <code>debtmanager.budgets</code> table reference
	 */
	public Budgets(java.lang.String alias) {
		this(alias, Budgets.BUDGETS);
	}

	private Budgets(java.lang.String alias, org.jooq.Table<BudgetsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Budgets(java.lang.String alias, org.jooq.Table<BudgetsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Debtmanager.DEBTMANAGER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<BudgetsRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_BUDGETS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<BudgetsRecord> getPrimaryKey() {
		return Keys.BUDGETS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<BudgetsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<BudgetsRecord>>asList(Keys.BUDGETS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<BudgetsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<BudgetsRecord, ?>>asList(Keys.BUDGETS__BUDGETS_OWNER_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Budgets as(java.lang.String alias) {
		return new Budgets(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Budgets rename(java.lang.String name) {
		return new Budgets(name, null);
	}
}
