/**
 * This class is generated by jOOQ
 */
package server.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Settlements extends org.jooq.impl.TableImpl<server.jooq.tables.records.SettlementsRecord> {

	private static final long serialVersionUID = -2140651017;

	/**
	 * The reference instance of <code>debtmanager.settlements</code>
	 */
	public static final server.jooq.tables.Settlements SETTLEMENTS = new server.jooq.tables.Settlements();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<server.jooq.tables.records.SettlementsRecord> getRecordType() {
		return server.jooq.tables.records.SettlementsRecord.class;
	}

	/**
	 * The column <code>debtmanager.settlements.id</code>.
	 */
	public final org.jooq.TableField<server.jooq.tables.records.SettlementsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>debtmanager.settlements.budget_id</code>.
	 */
	public final org.jooq.TableField<server.jooq.tables.records.SettlementsRecord, java.lang.Integer> BUDGET_ID = createField("budget_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>debtmanager.settlements.settle_date</code>.
	 */
	public final org.jooq.TableField<server.jooq.tables.records.SettlementsRecord, java.sql.Date> SETTLE_DATE = createField("settle_date", org.jooq.impl.SQLDataType.DATE.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>debtmanager.settlements</code> table reference
	 */
	public Settlements() {
		this("settlements", null);
	}

	/**
	 * Create an aliased <code>debtmanager.settlements</code> table reference
	 */
	public Settlements(java.lang.String alias) {
		this(alias, server.jooq.tables.Settlements.SETTLEMENTS);
	}

	private Settlements(java.lang.String alias, org.jooq.Table<server.jooq.tables.records.SettlementsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Settlements(java.lang.String alias, org.jooq.Table<server.jooq.tables.records.SettlementsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, server.jooq.Debtmanager.DEBTMANAGER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<server.jooq.tables.records.SettlementsRecord, java.lang.Integer> getIdentity() {
		return server.jooq.Keys.IDENTITY_SETTLEMENTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<server.jooq.tables.records.SettlementsRecord> getPrimaryKey() {
		return server.jooq.Keys.SETTLEMENTS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<server.jooq.tables.records.SettlementsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<server.jooq.tables.records.SettlementsRecord>>asList(server.jooq.Keys.SETTLEMENTS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<server.jooq.tables.records.SettlementsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<server.jooq.tables.records.SettlementsRecord, ?>>asList(server.jooq.Keys.SETTLEMENTS__SETTLEMENTS_BUDGET_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public server.jooq.tables.Settlements as(java.lang.String alias) {
		return new server.jooq.tables.Settlements(alias, this);
	}

	/**
	 * Rename this table
	 */
	public server.jooq.tables.Settlements rename(java.lang.String name) {
		return new server.jooq.tables.Settlements(name, null);
	}
}
