/**
 * This class is generated by jOOQ
 */
package tcs.javaproject.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Payments extends org.jooq.impl.TableImpl<tcs.javaproject.database.tables.records.PaymentsRecord> {

	private static final long serialVersionUID = 1593319603;

	/**
	 * The reference instance of <code>debtmanager.payments</code>
	 */
	public static final tcs.javaproject.database.tables.Payments PAYMENTS = new tcs.javaproject.database.tables.Payments();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tcs.javaproject.database.tables.records.PaymentsRecord> getRecordType() {
		return tcs.javaproject.database.tables.records.PaymentsRecord.class;
	}

	/**
	 * The column <code>debtmanager.payments.id</code>.
	 */
	public final org.jooq.TableField<tcs.javaproject.database.tables.records.PaymentsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>debtmanager.payments.term</code>.
	 */
	public final org.jooq.TableField<tcs.javaproject.database.tables.records.PaymentsRecord, java.sql.Date> TERM = createField("term", org.jooq.impl.SQLDataType.DATE.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>debtmanager.payments.budget_id</code>.
	 */
	public final org.jooq.TableField<tcs.javaproject.database.tables.records.PaymentsRecord, java.lang.Integer> BUDGET_ID = createField("budget_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>debtmanager.payments.user_id</code>.
	 */
	public final org.jooq.TableField<tcs.javaproject.database.tables.records.PaymentsRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>debtmanager.payments.description</code>.
	 */
	public final org.jooq.TableField<tcs.javaproject.database.tables.records.PaymentsRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>debtmanager.payments.amount</code>.
	 */
	public final org.jooq.TableField<tcs.javaproject.database.tables.records.PaymentsRecord, java.math.BigDecimal> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.NUMERIC.precision(6, 2).nullable(false), this, "");

	/**
	 * The column <code>debtmanager.payments.accounted</code>.
	 */
	public final org.jooq.TableField<tcs.javaproject.database.tables.records.PaymentsRecord, java.lang.Boolean> ACCOUNTED = createField("accounted", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * Create a <code>debtmanager.payments</code> table reference
	 */
	public Payments() {
		this("payments", null);
	}

	/**
	 * Create an aliased <code>debtmanager.payments</code> table reference
	 */
	public Payments(java.lang.String alias) {
		this(alias, tcs.javaproject.database.tables.Payments.PAYMENTS);
	}

	private Payments(java.lang.String alias, org.jooq.Table<tcs.javaproject.database.tables.records.PaymentsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Payments(java.lang.String alias, org.jooq.Table<tcs.javaproject.database.tables.records.PaymentsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tcs.javaproject.database.Debtmanager.DEBTMANAGER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<tcs.javaproject.database.tables.records.PaymentsRecord> getPrimaryKey() {
		return tcs.javaproject.database.Keys.PAYMENTS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<tcs.javaproject.database.tables.records.PaymentsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<tcs.javaproject.database.tables.records.PaymentsRecord>>asList(tcs.javaproject.database.Keys.PAYMENTS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<tcs.javaproject.database.tables.records.PaymentsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<tcs.javaproject.database.tables.records.PaymentsRecord, ?>>asList(tcs.javaproject.database.Keys.PAYMENTS__PAYMENTS_BUDGET_ID_FKEY, tcs.javaproject.database.Keys.PAYMENTS__PAYMENTS_USER_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tcs.javaproject.database.tables.Payments as(java.lang.String alias) {
		return new tcs.javaproject.database.tables.Payments(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tcs.javaproject.database.tables.Payments rename(java.lang.String name) {
		return new tcs.javaproject.database.tables.Payments(name, null);
	}
}
