/**
 * This class is generated by jOOQ
 */
package tcs.javaproject.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserBudget extends org.jooq.impl.TableImpl<tcs.javaproject.database.tables.records.UserBudgetRecord> {

	private static final long serialVersionUID = -584801333;

	/**
	 * The reference instance of <code>debtmanager.user_budget</code>
	 */
	public static final tcs.javaproject.database.tables.UserBudget USER_BUDGET = new tcs.javaproject.database.tables.UserBudget();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tcs.javaproject.database.tables.records.UserBudgetRecord> getRecordType() {
		return tcs.javaproject.database.tables.records.UserBudgetRecord.class;
	}

	/**
	 * The column <code>debtmanager.user_budget.user_id</code>.
	 */
	public final org.jooq.TableField<tcs.javaproject.database.tables.records.UserBudgetRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>debtmanager.user_budget.budget_id</code>.
	 */
	public final org.jooq.TableField<tcs.javaproject.database.tables.records.UserBudgetRecord, java.lang.Integer> BUDGET_ID = createField("budget_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>debtmanager.user_budget</code> table reference
	 */
	public UserBudget() {
		this("user_budget", null);
	}

	/**
	 * Create an aliased <code>debtmanager.user_budget</code> table reference
	 */
	public UserBudget(java.lang.String alias) {
		this(alias, tcs.javaproject.database.tables.UserBudget.USER_BUDGET);
	}

	private UserBudget(java.lang.String alias, org.jooq.Table<tcs.javaproject.database.tables.records.UserBudgetRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserBudget(java.lang.String alias, org.jooq.Table<tcs.javaproject.database.tables.records.UserBudgetRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tcs.javaproject.database.Debtmanager.DEBTMANAGER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<tcs.javaproject.database.tables.records.UserBudgetRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<tcs.javaproject.database.tables.records.UserBudgetRecord, ?>>asList(tcs.javaproject.database.Keys.USER_BUDGET__USER_BUDGET_USER_ID_FKEY, tcs.javaproject.database.Keys.USER_BUDGET__USER_BUDGET_BUDGET_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tcs.javaproject.database.tables.UserBudget as(java.lang.String alias) {
		return new tcs.javaproject.database.tables.UserBudget(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tcs.javaproject.database.tables.UserBudget rename(java.lang.String name) {
		return new tcs.javaproject.database.tables.UserBudget(name, null);
	}
}
