/**
 * This class is generated by jOOQ
 */
package server.jooq;

/**
 * Convenience access to all tables in debtmanager
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table debtmanager.bank_transfers
	 */
	public static final server.jooq.tables.BankTransfers BANK_TRANSFERS = server.jooq.tables.BankTransfers.BANK_TRANSFERS;

	/**
	 * The table debtmanager.budgets
	 */
	public static final server.jooq.tables.Budgets BUDGETS = server.jooq.tables.Budgets.BUDGETS;

	/**
	 * The table debtmanager.payments
	 */
	public static final server.jooq.tables.Payments PAYMENTS = server.jooq.tables.Payments.PAYMENTS;

	/**
	 * The table debtmanager.settlements
	 */
	public static final server.jooq.tables.Settlements SETTLEMENTS = server.jooq.tables.Settlements.SETTLEMENTS;

	/**
	 * The table debtmanager.user_budget
	 */
	public static final server.jooq.tables.UserBudget USER_BUDGET = server.jooq.tables.UserBudget.USER_BUDGET;

	/**
	 * The table debtmanager.users
	 */
	public static final server.jooq.tables.Users USERS = server.jooq.tables.Users.USERS;
}
