/**
 * This class is generated by jOOQ
 */
package server.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankTransfersRecord extends org.jooq.impl.UpdatableRecordImpl<server.jooq.tables.records.BankTransfersRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.math.BigDecimal, java.lang.Boolean> {

	private static final long serialVersionUID = 1787898103;

	/**
	 * Setter for <code>debtmanager.bank_transfers.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>debtmanager.bank_transfers.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>debtmanager.bank_transfers.settle_id</code>.
	 */
	public void setSettleId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>debtmanager.bank_transfers.settle_id</code>.
	 */
	public java.lang.Integer getSettleId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>debtmanager.bank_transfers.who</code>.
	 */
	public void setWho(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>debtmanager.bank_transfers.who</code>.
	 */
	public java.lang.Integer getWho() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>debtmanager.bank_transfers.whom</code>.
	 */
	public void setWhom(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>debtmanager.bank_transfers.whom</code>.
	 */
	public java.lang.Integer getWhom() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>debtmanager.bank_transfers.amount</code>.
	 */
	public void setAmount(java.math.BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>debtmanager.bank_transfers.amount</code>.
	 */
	public java.math.BigDecimal getAmount() {
		return (java.math.BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>debtmanager.bank_transfers.paid</code>.
	 */
	public void setPaid(java.lang.Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>debtmanager.bank_transfers.paid</code>.
	 */
	public java.lang.Boolean getPaid() {
		return (java.lang.Boolean) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.math.BigDecimal, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.math.BigDecimal, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return server.jooq.tables.BankTransfers.BANK_TRANSFERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return server.jooq.tables.BankTransfers.BANK_TRANSFERS.SETTLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return server.jooq.tables.BankTransfers.BANK_TRANSFERS.WHO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return server.jooq.tables.BankTransfers.BANK_TRANSFERS.WHOM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field5() {
		return server.jooq.tables.BankTransfers.BANK_TRANSFERS.AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field6() {
		return server.jooq.tables.BankTransfers.BANK_TRANSFERS.PAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getSettleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getWho();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getWhom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value5() {
		return getAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value6() {
		return getPaid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord value2(java.lang.Integer value) {
		setSettleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord value3(java.lang.Integer value) {
		setWho(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord value4(java.lang.Integer value) {
		setWhom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord value5(java.math.BigDecimal value) {
		setAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord value6(java.lang.Boolean value) {
		setPaid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.math.BigDecimal value5, java.lang.Boolean value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BankTransfersRecord
	 */
	public BankTransfersRecord() {
		super(server.jooq.tables.BankTransfers.BANK_TRANSFERS);
	}

	/**
	 * Create a detached, initialised BankTransfersRecord
	 */
	public BankTransfersRecord(java.lang.Integer id, java.lang.Integer settleId, java.lang.Integer who, java.lang.Integer whom, java.math.BigDecimal amount, java.lang.Boolean paid) {
		super(server.jooq.tables.BankTransfers.BANK_TRANSFERS);

		setValue(0, id);
		setValue(1, settleId);
		setValue(2, who);
		setValue(3, whom);
		setValue(4, amount);
		setValue(5, paid);
	}
}
