/**
 * This class is generated by jOOQ
 */
package server.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankTransfersRecord extends org.jooq.impl.UpdatableRecordImpl<server.jooq.tables.records.BankTransfersRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.math.BigDecimal, java.lang.Integer> {

	private static final long serialVersionUID = 1510925418;

	/**
	 * Setter for <code>debtmanager.bank_transfers.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>debtmanager.bank_transfers.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>debtmanager.bank_transfers.settlement_id</code>.
	 */
	public void setSettlementId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>debtmanager.bank_transfers.settlement_id</code>.
	 */
	public java.lang.Integer getSettlementId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>debtmanager.bank_transfers.sender</code>.
	 */
	public void setSender(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>debtmanager.bank_transfers.sender</code>.
	 */
	public java.lang.Integer getSender() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>debtmanager.bank_transfers.recipient</code>.
	 */
	public void setRecipient(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>debtmanager.bank_transfers.recipient</code>.
	 */
	public java.lang.Integer getRecipient() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>debtmanager.bank_transfers.amount</code>.
	 */
	public void setAmount(java.math.BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>debtmanager.bank_transfers.amount</code>.
	 */
	public java.math.BigDecimal getAmount() {
		return (java.math.BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>debtmanager.bank_transfers.status</code>.
	 */
	public void setStatus(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>debtmanager.bank_transfers.status</code>.
	 */
	public java.lang.Integer getStatus() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.math.BigDecimal, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.math.BigDecimal, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return server.jooq.tables.BankTransfers.BANK_TRANSFERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return server.jooq.tables.BankTransfers.BANK_TRANSFERS.SETTLEMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return server.jooq.tables.BankTransfers.BANK_TRANSFERS.SENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return server.jooq.tables.BankTransfers.BANK_TRANSFERS.RECIPIENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field5() {
		return server.jooq.tables.BankTransfers.BANK_TRANSFERS.AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return server.jooq.tables.BankTransfers.BANK_TRANSFERS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getSettlementId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getSender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getRecipient();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value5() {
		return getAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord value2(java.lang.Integer value) {
		setSettlementId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord value3(java.lang.Integer value) {
		setSender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord value4(java.lang.Integer value) {
		setRecipient(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord value5(java.math.BigDecimal value) {
		setAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord value6(java.lang.Integer value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BankTransfersRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.math.BigDecimal value5, java.lang.Integer value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BankTransfersRecord
	 */
	public BankTransfersRecord() {
		super(server.jooq.tables.BankTransfers.BANK_TRANSFERS);
	}

	/**
	 * Create a detached, initialised BankTransfersRecord
	 */
	public BankTransfersRecord(java.lang.Integer id, java.lang.Integer settlementId, java.lang.Integer sender, java.lang.Integer recipient, java.math.BigDecimal amount, java.lang.Integer status) {
		super(server.jooq.tables.BankTransfers.BANK_TRANSFERS);

		setValue(0, id);
		setValue(1, settlementId);
		setValue(2, sender);
		setValue(3, recipient);
		setValue(4, amount);
		setValue(5, status);
	}
}
