/**
 * This class is generated by jOOQ
 */
package server.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentsRecord extends org.jooq.impl.UpdatableRecordImpl<server.jooq.tables.records.PaymentsRecord> implements org.jooq.Record8<java.lang.Integer, java.sql.Date, java.lang.Integer, java.lang.Integer, java.lang.String, java.math.BigDecimal, java.lang.Integer, java.lang.Boolean> {

	private static final long serialVersionUID = 1257963493;

	/**
	 * Setter for <code>debtmanager.payments.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>debtmanager.payments.term</code>.
	 */
	public void setTerm(java.sql.Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.term</code>.
	 */
	public java.sql.Date getTerm() {
		return (java.sql.Date) getValue(1);
	}

	/**
	 * Setter for <code>debtmanager.payments.budget_id</code>.
	 */
	public void setBudgetId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.budget_id</code>.
	 */
	public java.lang.Integer getBudgetId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>debtmanager.payments.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>debtmanager.payments.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>debtmanager.payments.amount</code>.
	 */
	public void setAmount(java.math.BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.amount</code>.
	 */
	public java.math.BigDecimal getAmount() {
		return (java.math.BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>debtmanager.payments.settlement_id</code>.
	 */
	public void setSettlementId(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.settlement_id</code>.
	 */
	public java.lang.Integer getSettlementId() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>debtmanager.payments.accounted</code>.
	 */
	public void setAccounted(java.lang.Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.accounted</code>.
	 */
	public java.lang.Boolean getAccounted() {
		return (java.lang.Boolean) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.sql.Date, java.lang.Integer, java.lang.Integer, java.lang.String, java.math.BigDecimal, java.lang.Integer, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.sql.Date, java.lang.Integer, java.lang.Integer, java.lang.String, java.math.BigDecimal, java.lang.Integer, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return server.jooq.tables.Payments.PAYMENTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field2() {
		return server.jooq.tables.Payments.PAYMENTS.TERM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return server.jooq.tables.Payments.PAYMENTS.BUDGET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return server.jooq.tables.Payments.PAYMENTS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return server.jooq.tables.Payments.PAYMENTS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field6() {
		return server.jooq.tables.Payments.PAYMENTS.AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return server.jooq.tables.Payments.PAYMENTS.SETTLEMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field8() {
		return server.jooq.tables.Payments.PAYMENTS.ACCOUNTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value2() {
		return getTerm();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getBudgetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value6() {
		return getAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getSettlementId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value8() {
		return getAccounted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value2(java.sql.Date value) {
		setTerm(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value3(java.lang.Integer value) {
		setBudgetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value4(java.lang.Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value5(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value6(java.math.BigDecimal value) {
		setAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value7(java.lang.Integer value) {
		setSettlementId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value8(java.lang.Boolean value) {
		setAccounted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord values(java.lang.Integer value1, java.sql.Date value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.String value5, java.math.BigDecimal value6, java.lang.Integer value7, java.lang.Boolean value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PaymentsRecord
	 */
	public PaymentsRecord() {
		super(server.jooq.tables.Payments.PAYMENTS);
	}

	/**
	 * Create a detached, initialised PaymentsRecord
	 */
	public PaymentsRecord(java.lang.Integer id, java.sql.Date term, java.lang.Integer budgetId, java.lang.Integer userId, java.lang.String description, java.math.BigDecimal amount, java.lang.Integer settlementId, java.lang.Boolean accounted) {
		super(server.jooq.tables.Payments.PAYMENTS);

		setValue(0, id);
		setValue(1, term);
		setValue(2, budgetId);
		setValue(3, userId);
		setValue(4, description);
		setValue(5, amount);
		setValue(6, settlementId);
		setValue(7, accounted);
	}
}
