/**
 * This class is generated by jOOQ
 */
package server.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentsRecord extends org.jooq.impl.UpdatableRecordImpl<server.jooq.tables.records.PaymentsRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.math.BigDecimal, java.lang.Integer, java.lang.Boolean> {

	private static final long serialVersionUID = 1304723761;

	/**
	 * Setter for <code>debtmanager.payments.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>debtmanager.payments.budget_id</code>.
	 */
	public void setBudgetId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.budget_id</code>.
	 */
	public java.lang.Integer getBudgetId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>debtmanager.payments.payer_id</code>.
	 */
	public void setPayerId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.payer_id</code>.
	 */
	public java.lang.Integer getPayerId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>debtmanager.payments.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>debtmanager.payments.amount</code>.
	 */
	public void setAmount(java.math.BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.amount</code>.
	 */
	public java.math.BigDecimal getAmount() {
		return (java.math.BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>debtmanager.payments.settlement_id</code>.
	 */
	public void setSettlementId(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.settlement_id</code>.
	 */
	public java.lang.Integer getSettlementId() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>debtmanager.payments.settled</code>.
	 */
	public void setSettled(java.lang.Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>debtmanager.payments.settled</code>.
	 */
	public java.lang.Boolean getSettled() {
		return (java.lang.Boolean) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.math.BigDecimal, java.lang.Integer, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.math.BigDecimal, java.lang.Integer, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return server.jooq.tables.Payments.PAYMENTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return server.jooq.tables.Payments.PAYMENTS.BUDGET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return server.jooq.tables.Payments.PAYMENTS.PAYER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return server.jooq.tables.Payments.PAYMENTS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field5() {
		return server.jooq.tables.Payments.PAYMENTS.AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return server.jooq.tables.Payments.PAYMENTS.SETTLEMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field7() {
		return server.jooq.tables.Payments.PAYMENTS.SETTLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getBudgetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getPayerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value5() {
		return getAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getSettlementId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value7() {
		return getSettled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value2(java.lang.Integer value) {
		setBudgetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value3(java.lang.Integer value) {
		setPayerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value4(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value5(java.math.BigDecimal value) {
		setAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value6(java.lang.Integer value) {
		setSettlementId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord value7(java.lang.Boolean value) {
		setSettled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PaymentsRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.String value4, java.math.BigDecimal value5, java.lang.Integer value6, java.lang.Boolean value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PaymentsRecord
	 */
	public PaymentsRecord() {
		super(server.jooq.tables.Payments.PAYMENTS);
	}

	/**
	 * Create a detached, initialised PaymentsRecord
	 */
	public PaymentsRecord(java.lang.Integer id, java.lang.Integer budgetId, java.lang.Integer payerId, java.lang.String description, java.math.BigDecimal amount, java.lang.Integer settlementId, java.lang.Boolean settled) {
		super(server.jooq.tables.Payments.PAYMENTS);

		setValue(0, id);
		setValue(1, budgetId);
		setValue(2, payerId);
		setValue(3, description);
		setValue(4, amount);
		setValue(5, settlementId);
		setValue(6, settled);
	}
}
