/**
 * This class is generated by jOOQ
 */
package server.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettlementsRecord extends org.jooq.impl.UpdatableRecordImpl<server.jooq.tables.records.SettlementsRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.sql.Date> {

	private static final long serialVersionUID = 651606876;

	/**
	 * Setter for <code>debtmanager.settlements.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>debtmanager.settlements.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>debtmanager.settlements.budget_id</code>.
	 */
	public void setBudgetId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>debtmanager.settlements.budget_id</code>.
	 */
	public java.lang.Integer getBudgetId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>debtmanager.settlements.settle_date</code>.
	 */
	public void setSettleDate(java.sql.Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>debtmanager.settlements.settle_date</code>.
	 */
	public java.sql.Date getSettleDate() {
		return (java.sql.Date) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.sql.Date> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.sql.Date> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return server.jooq.tables.Settlements.SETTLEMENTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return server.jooq.tables.Settlements.SETTLEMENTS.BUDGET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field3() {
		return server.jooq.tables.Settlements.SETTLEMENTS.SETTLE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getBudgetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value3() {
		return getSettleDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettlementsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettlementsRecord value2(java.lang.Integer value) {
		setBudgetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettlementsRecord value3(java.sql.Date value) {
		setSettleDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettlementsRecord values(java.lang.Integer value1, java.lang.Integer value2, java.sql.Date value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SettlementsRecord
	 */
	public SettlementsRecord() {
		super(server.jooq.tables.Settlements.SETTLEMENTS);
	}

	/**
	 * Create a detached, initialised SettlementsRecord
	 */
	public SettlementsRecord(java.lang.Integer id, java.lang.Integer budgetId, java.sql.Date settleDate) {
		super(server.jooq.tables.Settlements.SETTLEMENTS);

		setValue(0, id);
		setValue(1, budgetId);
		setValue(2, settleDate);
	}
}
