/**
 * This class is generated by jOOQ
 */
package tcs.javaproject.database;

/**
 * A class modelling foreign key relationships between tables of the <code>debtmanager</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<tcs.javaproject.database.tables.records.BudgetsRecord, java.lang.Integer> IDENTITY_BUDGETS = Identities0.IDENTITY_BUDGETS;
	public static final org.jooq.Identity<tcs.javaproject.database.tables.records.UsersRecord, java.lang.Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<tcs.javaproject.database.tables.records.BudgetsRecord> BUDGETS_PKEY = UniqueKeys0.BUDGETS_PKEY;
	public static final org.jooq.UniqueKey<tcs.javaproject.database.tables.records.UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;
	public static final org.jooq.UniqueKey<tcs.javaproject.database.tables.records.UsersRecord> USERS_EMAIL_KEY = UniqueKeys0.USERS_EMAIL_KEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<tcs.javaproject.database.tables.records.BudgetsRecord, tcs.javaproject.database.tables.records.UsersRecord> BUDGETS__BUDGETS_OWNER_ID_FKEY = ForeignKeys0.BUDGETS__BUDGETS_OWNER_ID_FKEY;
	public static final org.jooq.ForeignKey<tcs.javaproject.database.tables.records.UserBudgetRecord, tcs.javaproject.database.tables.records.UsersRecord> USER_BUDGET__USER_BUDGET_USER_ID_FKEY = ForeignKeys0.USER_BUDGET__USER_BUDGET_USER_ID_FKEY;
	public static final org.jooq.ForeignKey<tcs.javaproject.database.tables.records.UserBudgetRecord, tcs.javaproject.database.tables.records.BudgetsRecord> USER_BUDGET__USER_BUDGET_BUDGET_ID_FKEY = ForeignKeys0.USER_BUDGET__USER_BUDGET_BUDGET_ID_FKEY;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<tcs.javaproject.database.tables.records.BudgetsRecord, java.lang.Integer> IDENTITY_BUDGETS = createIdentity(tcs.javaproject.database.tables.Budgets.BUDGETS, tcs.javaproject.database.tables.Budgets.BUDGETS.ID);
		public static org.jooq.Identity<tcs.javaproject.database.tables.records.UsersRecord, java.lang.Integer> IDENTITY_USERS = createIdentity(tcs.javaproject.database.tables.Users.USERS, tcs.javaproject.database.tables.Users.USERS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<tcs.javaproject.database.tables.records.BudgetsRecord> BUDGETS_PKEY = createUniqueKey(tcs.javaproject.database.tables.Budgets.BUDGETS, tcs.javaproject.database.tables.Budgets.BUDGETS.ID);
		public static final org.jooq.UniqueKey<tcs.javaproject.database.tables.records.UsersRecord> USERS_PKEY = createUniqueKey(tcs.javaproject.database.tables.Users.USERS, tcs.javaproject.database.tables.Users.USERS.ID);
		public static final org.jooq.UniqueKey<tcs.javaproject.database.tables.records.UsersRecord> USERS_EMAIL_KEY = createUniqueKey(tcs.javaproject.database.tables.Users.USERS, tcs.javaproject.database.tables.Users.USERS.EMAIL);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<tcs.javaproject.database.tables.records.BudgetsRecord, tcs.javaproject.database.tables.records.UsersRecord> BUDGETS__BUDGETS_OWNER_ID_FKEY = createForeignKey(tcs.javaproject.database.Keys.USERS_PKEY, tcs.javaproject.database.tables.Budgets.BUDGETS, tcs.javaproject.database.tables.Budgets.BUDGETS.OWNER_ID);
		public static final org.jooq.ForeignKey<tcs.javaproject.database.tables.records.UserBudgetRecord, tcs.javaproject.database.tables.records.UsersRecord> USER_BUDGET__USER_BUDGET_USER_ID_FKEY = createForeignKey(tcs.javaproject.database.Keys.USERS_PKEY, tcs.javaproject.database.tables.UserBudget.USER_BUDGET, tcs.javaproject.database.tables.UserBudget.USER_BUDGET.USER_ID);
		public static final org.jooq.ForeignKey<tcs.javaproject.database.tables.records.UserBudgetRecord, tcs.javaproject.database.tables.records.BudgetsRecord> USER_BUDGET__USER_BUDGET_BUDGET_ID_FKEY = createForeignKey(tcs.javaproject.database.Keys.BUDGETS_PKEY, tcs.javaproject.database.tables.UserBudget.USER_BUDGET, tcs.javaproject.database.tables.UserBudget.USER_BUDGET.BUDGET_ID);
	}
}
