/**
 * This class is generated by jOOQ
 */
package tcs.javaproject.database;

/**
 * Convenience access to all tables in debtmanager
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table debtmanager.budgets
	 */
	public static final tcs.javaproject.database.tables.Budgets BUDGETS = tcs.javaproject.database.tables.Budgets.BUDGETS;

	/**
	 * The table debtmanager.payments
	 */
	public static final tcs.javaproject.database.tables.Payments PAYMENTS = tcs.javaproject.database.tables.Payments.PAYMENTS;

	/**
	 * The table debtmanager.user_budget
	 */
	public static final tcs.javaproject.database.tables.UserBudget USER_BUDGET = tcs.javaproject.database.tables.UserBudget.USER_BUDGET;

	/**
	 * The table debtmanager.users
	 */
	public static final tcs.javaproject.database.tables.Users USERS = tcs.javaproject.database.tables.Users.USERS;
}
